/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2_zoo;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author joanaibarra
 */
public class zoogisticsFrame extends JFrame {

    /**
     * Creates new form zoogisticsFrame
     */
    public zoogisticsFrame() {
        super("Zoogistics");
        this.setSize(600, 550); //size may change 
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth())/2);
        int y = (int) ((screen.getHeight() - getHeight())/2);
        setLocation(x, y); 
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        logButton = new javax.swing.JButton();
        nxtupButton = new javax.swing.JButton();
        mvButton = new javax.swing.JButton();
        addanButton = new javax.swing.JButton();
        logPanel = new javax.swing.JPanel();
        logHeader = new javax.swing.JLabel();
        homeButton1 = new javax.swing.JButton();
        question2 = new javax.swing.JLabel();
        logFeed = new javax.swing.JRadioButton();
        logMedication = new javax.swing.JRadioButton();
        question1 = new javax.swing.JLabel();
        searchAnimal = new javax.swing.JTextField();
        submitButton3 = new javax.swing.JButton();
        hint = new javax.swing.JLabel();
        mvPanel = new javax.swing.JPanel();
        mvHeader = new javax.swing.JLabel();
        homeButton2 = new javax.swing.JButton();
        question3 = new javax.swing.JLabel();
        animalSearch2 = new javax.swing.JTextField();
        question4 = new javax.swing.JLabel();
        exhibitSearch = new javax.swing.JTextField();
        submitButton2 = new javax.swing.JButton();
        hint1 = new javax.swing.JLabel();
        hint2 = new javax.swing.JLabel();
        nxtupPanel = new javax.swing.JPanel();
        nxtupHeader = new javax.swing.JLabel();
        homeButton3 = new javax.swing.JButton();
        dataEntriesPanel = new javax.swing.JPanel();
        addanPanel = new javax.swing.JPanel();
        addanHeader = new javax.swing.JLabel();
        homeButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelExhibit = new javax.swing.JLabel();
        jLabelLf = new javax.swing.JLabel();
        jLabelnxtAct = new javax.swing.JLabel();
        jTfName = new javax.swing.JTextField();
        jTfNxtAct = new javax.swing.JTextField();
        jTfFeed = new javax.swing.JTextField();
        jTfExhibit = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabelType = new javax.swing.JLabel();
        jTfType = new javax.swing.JTextField();
        jLabelSex = new javax.swing.JLabel();
        jTfSex = new javax.swing.JTextField();
        successPanel = new javax.swing.JPanel();
        successHeader = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        rtnhomeButton = new javax.swing.JButton();
        msg2contd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        titleLabel.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        titleLabel.setText("Zoogistics");

        logButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        logButton.setText("Log Activity");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        nxtupButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        nxtupButton.setText("Next Up");
        nxtupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtupButtonActionPerformed(evt);
            }
        });

        mvButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        mvButton.setText("Move Animal");
        mvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvButtonActionPerformed(evt);
            }
        });

        addanButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        addanButton.setText("Add Animal");
        addanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nxtupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mvButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nxtupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(678, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "homePanel");

        logPanel.setMaximumSize(new java.awt.Dimension(3000, 3000));
        logPanel.setPreferredSize(new java.awt.Dimension(700, 800));

        logHeader.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        logHeader.setText("Log an Activity");

        homeButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        homeButton1.setText("Home");
        homeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton1ActionPerformed(evt);
            }
        });

        question2.setText("Step 2: Who would you like to log an activity for?");

        logFeed.setText("Log Feeding");
        logFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logFeedActionPerformed(evt);
            }
        });

        logMedication.setText("Log Medication");

        question1.setText("Step 1: What kind of activity are you logging? (Choose 1)");

        submitButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        submitButton3.setText("Submit");

        hint.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        hint.setText("you can search by name, type or ID");

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton3)
                        .addGap(64, 64, 64)
                        .addComponent(homeButton1))
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(logFeed)
                        .addGap(155, 155, 155)
                        .addComponent(logMedication)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(94, 94, 94))
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addComponent(logHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(440, Short.MAX_VALUE))
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hint)
                            .addComponent(question1)
                            .addComponent(question2)
                            .addComponent(searchAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logFeed)
                    .addComponent(logMedication))
                .addGap(32, 32, 32)
                .addComponent(question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 601, Short.MAX_VALUE)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton3)
                    .addComponent(homeButton1))
                .addGap(55, 55, 55))
        );

        mainPanel.add(logPanel, "logPanel");

        mvHeader.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        mvHeader.setText("Move an Animal");

        homeButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        homeButton2.setText("Home");
        homeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton2ActionPerformed(evt);
            }
        });

        question3.setText("Step 1: Who would you like to move?");

        animalSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalSearch2ActionPerformed(evt);
            }
        });

        question4.setText("Step 2: Where To?");

        submitButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        submitButton2.setText("Submit");
        submitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton2ActionPerformed(evt);
            }
        });

        hint1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        hint1.setText("you can search by name, type or ID");

        hint2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        hint2.setText("search by exhibit name");

        javax.swing.GroupLayout mvPanelLayout = new javax.swing.GroupLayout(mvPanel);
        mvPanel.setLayout(mvPanelLayout);
        mvPanelLayout.setHorizontalGroup(
            mvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mvPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton2)
                .addGap(37, 37, 37)
                .addComponent(homeButton2)
                .addGap(80, 80, 80))
            .addGroup(mvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exhibitSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animalSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mvHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question4)
                    .addGroup(mvPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(mvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hint1)
                            .addComponent(question3)))
                    .addComponent(hint2))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        mvPanelLayout.setVerticalGroup(
            mvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mvHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question3)
                .addGap(3, 3, 3)
                .addComponent(hint1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animalSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(question4)
                .addGap(4, 4, 4)
                .addComponent(hint2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exhibitSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addGroup(mvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton2)
                    .addComponent(homeButton2))
                .addGap(59, 59, 59))
        );

        mainPanel.add(mvPanel, "mvPanel");

        nxtupHeader.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        nxtupHeader.setText("What's Next Up");

        homeButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        homeButton3.setText("Home");
        homeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton3ActionPerformed(evt);
            }
        });

        dataEntriesPanel.setBackground(new java.awt.Color(218, 243, 249));

        javax.swing.GroupLayout dataEntriesPanelLayout = new javax.swing.GroupLayout(dataEntriesPanel);
        dataEntriesPanel.setLayout(dataEntriesPanelLayout);
        dataEntriesPanelLayout.setHorizontalGroup(
            dataEntriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        dataEntriesPanelLayout.setVerticalGroup(
            dataEntriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout nxtupPanelLayout = new javax.swing.GroupLayout(nxtupPanel);
        nxtupPanel.setLayout(nxtupPanelLayout);
        nxtupPanelLayout.setHorizontalGroup(
            nxtupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nxtupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nxtupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nxtupPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeButton3))
                    .addGroup(nxtupPanelLayout.createSequentialGroup()
                        .addComponent(nxtupHeader)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(nxtupPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(dataEntriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        nxtupPanelLayout.setVerticalGroup(
            nxtupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nxtupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nxtupHeader)
                .addGap(31, 31, 31)
                .addComponent(dataEntriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeButton3)
                .addContainerGap())
        );

        mainPanel.add(nxtupPanel, "nxtupPanel");

        addanHeader.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        addanHeader.setText("Add New Animal");

        homeButton4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        homeButton4.setText("Home");
        homeButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("All fields are required! ");

        jLabelName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelName.setText("Name:");

        jLabelExhibit.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelExhibit.setText("Exhibit:");

        jLabelLf.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelLf.setText("Last Feeding:");

        jLabelnxtAct.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelnxtAct.setText("Next Activity:");

        jTfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfNameActionPerformed(evt);
            }
        });

        jTfNxtAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfNxtActActionPerformed(evt);
            }
        });

        jTfFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfFeedActionPerformed(evt);
            }
        });

        jTfExhibit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfExhibitActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabelType.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelType.setText("Type:");

        jLabelSex.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabelSex.setText("Sex:");

        javax.swing.GroupLayout addanPanelLayout = new javax.swing.GroupLayout(addanPanel);
        addanPanel.setLayout(addanPanelLayout);
        addanPanelLayout.setHorizontalGroup(
            addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addanPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addanPanelLayout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addGap(63, 63, 63))
                            .addGroup(addanPanelLayout.createSequentialGroup()
                                .addComponent(jLabelExhibit)
                                .addGap(50, 50, 50)))
                        .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfName, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addanPanelLayout.createSequentialGroup()
                                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfType, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabelSex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTfSex, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(185, 185, 185))
                    .addGroup(addanPanelLayout.createSequentialGroup()
                        .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addanPanelLayout.createSequentialGroup()
                                .addComponent(jLabelnxtAct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfNxtAct, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                            .addComponent(addanHeader, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addanPanelLayout.createSequentialGroup()
                                .addComponent(jLabelLf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfExhibit, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                                    .addComponent(jTfFeed))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(49, 49, 49)
                .addComponent(homeButton4)
                .addGap(135, 135, 135))
        );
        addanPanelLayout.setVerticalGroup(
            addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addanHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTfSex, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTfType, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSex)))
                .addGap(12, 12, 12)
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addGap(18, 18, 18)
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfExhibit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExhibit))
                .addGap(47, 47, 47)
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLf)
                    .addComponent(jTfFeed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfNxtAct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnxtAct, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(addanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(homeButton4))
                .addGap(74, 74, 74))
        );

        mainPanel.add(addanPanel, "addanPanel");

        successHeader.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        successHeader.setText("Success!");

        msg1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        msg1.setText("Thank you for using Zoogistics!");

        msg2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        msg2.setText("You have successfully");

        rtnhomeButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rtnhomeButton.setText("Return Home");
        rtnhomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtnhomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout successPanelLayout = new javax.swing.GroupLayout(successPanel);
        successPanel.setLayout(successPanelLayout);
        successPanelLayout.setHorizontalGroup(
            successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(successPanelLayout.createSequentialGroup()
                        .addComponent(successHeader)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successPanelLayout.createSequentialGroup()
                        .addGap(0, 214, Short.MAX_VALUE)
                        .addGroup(successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtnhomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msg1)
                            .addGroup(successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(msg2contd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successPanelLayout.createSequentialGroup()
                                    .addComponent(msg2)
                                    .addGap(42, 42, 42))))
                        .addGap(218, 218, 218))))
        );
        successPanelLayout.setVerticalGroup(
            successPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(successHeader)
                .addGap(62, 62, 62)
                .addComponent(msg1)
                .addGap(18, 18, 18)
                .addComponent(msg2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg2contd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(rtnhomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(588, Short.MAX_VALUE))
        );

        mainPanel.add(successPanel, "successPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "logPanel");
    }//GEN-LAST:event_logButtonActionPerformed

    private void mvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mvPanel");
    }//GEN-LAST:event_mvButtonActionPerformed

    private void nxtupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtupButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "nxtupPanel");
    }//GEN-LAST:event_nxtupButtonActionPerformed

    private void addanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addanButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addanPanel");
    }//GEN-LAST:event_addanButtonActionPerformed

    private void homeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton1ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_homeButton1ActionPerformed

    private void homeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton2ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_homeButton2ActionPerformed

    private void homeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton3ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_homeButton3ActionPerformed

    private void homeButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton4ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_homeButton4ActionPerformed

    private void logFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logFeedActionPerformed

    private void animalSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalSearch2ActionPerformed

    private void jTfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfNameActionPerformed

    private void jTfNxtActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfNxtActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfNxtActActionPerformed

    private void jTfFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfFeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfFeedActionPerformed

    private void jTfExhibitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfExhibitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfExhibitActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "successPanel");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void rtnhomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtnhomeButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_rtnhomeButtonActionPerformed

    private void submitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton2ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "successPanel");
    }//GEN-LAST:event_submitButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zoogisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zoogisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zoogisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zoogisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zoogisticsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addanButton;
    private javax.swing.JLabel addanHeader;
    private javax.swing.JPanel addanPanel;
    private javax.swing.JTextField animalSearch2;
    private javax.swing.JPanel dataEntriesPanel;
    private javax.swing.JTextField exhibitSearch;
    private javax.swing.JLabel hint;
    private javax.swing.JLabel hint1;
    private javax.swing.JLabel hint2;
    private javax.swing.JButton homeButton1;
    private javax.swing.JButton homeButton2;
    private javax.swing.JButton homeButton3;
    private javax.swing.JButton homeButton4;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelExhibit;
    private javax.swing.JLabel jLabelLf;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelnxtAct;
    private javax.swing.JTextField jTfExhibit;
    private javax.swing.JTextField jTfFeed;
    private javax.swing.JTextField jTfName;
    private javax.swing.JTextField jTfNxtAct;
    private javax.swing.JTextField jTfSex;
    private javax.swing.JTextField jTfType;
    private javax.swing.JButton logButton;
    private javax.swing.JRadioButton logFeed;
    private javax.swing.JLabel logHeader;
    private javax.swing.JRadioButton logMedication;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel msg2contd;
    private javax.swing.JButton mvButton;
    private javax.swing.JLabel mvHeader;
    private javax.swing.JPanel mvPanel;
    private javax.swing.JButton nxtupButton;
    private javax.swing.JLabel nxtupHeader;
    private javax.swing.JPanel nxtupPanel;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JButton rtnhomeButton;
    private javax.swing.JTextField searchAnimal;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitButton2;
    private javax.swing.JButton submitButton3;
    private javax.swing.JLabel successHeader;
    private javax.swing.JPanel successPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
